### ISSUE TITLE
Can't send request

### ISSUE THREAD

**Issue by smaragdus** [VgaCich/AriaUI#1]
No matter what settings I try I always get an error:

`Can't send request`

**screen:**

![Aria UI 1 0 alpha (28 02 2019) - 2022-04-24 - 006](https://user-images.githubusercontent.com/9025757/164965200-50f7b257-3c1c-4322-a54c-ff3e88d06617.png)

Any tips?

**Comment by VgaCich** [comment]
There is no connection to aria2 (indicated in status bar). Check server settings in AriaUI, check aria2 settings (run as daemon, enable rpc, set autenthification, etc). Also you should run aria2 as daemon manually, AriaUI is only RPC-GUI.

**Comment by VgaCich** [comment]
Here is my aria2 settings. You need at least first four lines.
```
daemon=true
enable-rpc=true
rpc-listen-all=true
rpc-secret=<insert your token>
rpc-save-upload-metadata=false
force-save=true
keep-unfinished-download-result=true
save-session=session.aria2
save-session-interval=300
enable-dht=true
enable-peer-exchange=true
bt-enable-lpd=true
bt-save-metadata=false
bt-detach-seed-only=true
bt-prioritize-piece=head,tail
bt-remove-unselected-file=true
bt-seed-unverified=true
check-integrity=false
follow-torrent=mem
file-allocation=falloc
input-file=session.aria2
```

**Comment by smaragdus** [comment]
@VgaCich 

Thank you very much for your quick, detailed and helpful response!

> Also you should run aria2 as daemon manually, AriaUI is only RPC-GUI.

I missed this completely.

Best regards!
